CREATE ALIAS IF NOT EXISTS DATE_FORMAT FOR "com.ams.test.H2Functions.dateFormat";

ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS avatar VARCHAR(255);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS login_ip VARCHAR(128);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS login_date DATETIME;
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS remark VARCHAR(512);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS update_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS deleted TINYINT DEFAULT 0;

ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS role_key VARCHAR(100);
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS data_scope VARCHAR(32);
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS menu_check_strictly TINYINT DEFAULT 1;
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS dept_check_strictly TINYINT DEFAULT 1;
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS deleted TINYINT DEFAULT 0;

ALTER TABLE sys_dept ADD COLUMN IF NOT EXISTS deleted TINYINT DEFAULT 0;
ALTER TABLE sys_dept ADD COLUMN IF NOT EXISTS ancestors VARCHAR(512) DEFAULT '';
ALTER TABLE sys_dept ADD COLUMN IF NOT EXISTS email VARCHAR(128);
ALTER TABLE sys_dept ADD COLUMN IF NOT EXISTS leader_id BIGINT;
ALTER TABLE sys_dept ADD COLUMN IF NOT EXISTS secretary_id BIGINT;
ALTER TABLE sys_dept ADD COLUMN IF NOT EXISTS dept_type VARCHAR(32) DEFAULT '';
ALTER TABLE sys_dept ADD COLUMN IF NOT EXISTS description VARCHAR(512);

CREATE TABLE IF NOT EXISTS sys_menu (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    menu_name VARCHAR(128) NOT NULL,
    parent_id BIGINT DEFAULT 0,
    sort_order INT DEFAULT 0,
    path VARCHAR(256),
    component VARCHAR(256),
    query_param VARCHAR(256),
    route_name VARCHAR(128),
    menu_type CHAR(1) NOT NULL DEFAULT 'M',
    visible TINYINT DEFAULT 1,
    status TINYINT DEFAULT 1,
    perms VARCHAR(128),
    icon VARCHAR(128),
    is_frame TINYINT DEFAULT 1,
    is_cache TINYINT DEFAULT 1,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sys_role_menu (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_role_dept (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    role_id BIGINT NOT NULL,
    dept_id BIGINT NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE asset ADD COLUMN IF NOT EXISTS abc_classification VARCHAR(16);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS purchase_cost DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE asset ADD COLUMN IF NOT EXISTS depreciation_method VARCHAR(32);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS total_expected_units DECIMAL(15,2);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS actual_units DECIMAL(15,2);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS location_id BIGINT;
ALTER TABLE asset ADD COLUMN IF NOT EXISTS location_lat DECIMAL(10,6);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS location_lng DECIMAL(10,6);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS deleted TINYINT DEFAULT 0;
ALTER TABLE asset ADD COLUMN IF NOT EXISTS create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE asset ADD COLUMN IF NOT EXISTS update_time DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE asset_category ADD COLUMN IF NOT EXISTS fieldset_id BIGINT;

ALTER TABLE approval_process ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;

CREATE TABLE IF NOT EXISTS depreciation_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL,
    asset_id BIGINT NOT NULL,
    method VARCHAR(32) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    depreciation_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    book_value_before DECIMAL(12,2),
    book_value_after DECIMAL(12,2),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME,
    deleted TINYINT DEFAULT 0
);

ALTER TABLE work_order ADD COLUMN IF NOT EXISTS collaborators TEXT;
ALTER TABLE work_order ADD COLUMN IF NOT EXISTS attachments TEXT;
ALTER TABLE work_order ADD COLUMN IF NOT EXISTS fault_code_id BIGINT;
ALTER TABLE work_order ADD COLUMN IF NOT EXISTS sla_deadline DATETIME;
ALTER TABLE work_order ADD COLUMN IF NOT EXISTS sla_status VARCHAR(32) DEFAULT 'NORMAL';

CREATE TABLE IF NOT EXISTS sys_channel_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'dept:1',
    channel_type VARCHAR(32) NOT NULL,
    config_name VARCHAR(128) NOT NULL,
    webhook_url VARCHAR(512) NOT NULL,
    secret VARCHAR(256),
    enabled TINYINT DEFAULT 1,
    description VARCHAR(512),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME
);

CREATE TABLE IF NOT EXISTS notification_template (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id VARCHAR(64) DEFAULT 'dept:1',
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(128),
    category VARCHAR(64) DEFAULT 'general',
    channel_type VARCHAR(32) DEFAULT 'ALL',
    title_template VARCHAR(256),
    content_template TEXT,
    variables TEXT,
    is_builtin TINYINT DEFAULT 0,
    status TINYINT DEFAULT 1,
    create_by VARCHAR(64),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(64),
    update_time DATETIME,
    deleted TINYINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sys_webhook_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'dept:1',
    name VARCHAR(100) NOT NULL,
    url VARCHAR(500) NOT NULL,
    secret VARCHAR(200),
    events TEXT,
    enabled TINYINT DEFAULT 1,
    description VARCHAR(500),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME
);

CREATE TABLE IF NOT EXISTS maintenance_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'dept:1',
    asset_id BIGINT NOT NULL,
    work_order_id BIGINT,
    maintenance_type VARCHAR(32) DEFAULT 'REPAIR',
    source_type VARCHAR(16) DEFAULT 'MANUAL',
    maintenance_date DATE,
    next_maintenance_date DATE,
    cost DECIMAL(10,2) DEFAULT 0.00,
    executor VARCHAR(128),
    content TEXT,
    result VARCHAR(32),
    remark TEXT,
    create_by BIGINT,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS business_comment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    business_type VARCHAR(32) NOT NULL,
    business_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    parent_comment_id BIGINT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'dept:1',
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME
);
