import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const readText = (relativePath: string) => readFileSync(new URL(relativePath, import.meta.url), 'utf8');

const registrySource = readText('../pages/workspace-preview/system-hub/systemRealPageRegistry.ts');
const moduleSource = readText('../pages/workspace-preview/system-hub/systemModuleRegistry.ts');
const interfacesApi = readText('../api/systemInterfaces.ts');
const fieldMappingsApi = readText('../api/systemFieldMappings.ts');
const syncRulesApi = readText('../api/systemSyncRules.ts');
const webhookConfigsApi = readText('../api/systemWebhookConfigs.ts');
const externalSystemsApi = readText('../api/systemExternalSystems.ts');
const systemConfigApi = readText('../api/systemConfig.ts');
const auditApi = readText('../api/audit.ts');
const cacheManagementApi = readText('../api/cacheManagement.ts');
const fileStorageApi = readText('../api/fileStorage.ts');
const assetCategoriesApi = readText('../api/assetCategories.ts');
const numberingRulesApi = readText('../api/numberingRules.ts');
const customFieldApi = readText('../api/customField.ts');
const vendorsApi = readText('../api/vendors.ts');
const locationsApi = readText('../api/locations.ts');
const userManagementApi = readText('../api/userManagement.ts');
const deptsApi = readText('../api/depts.ts');
const rolePermissionsApi = readText('../api/rolePermissions.ts');
const workflowDefinitionsApi = readText('../api/workflowDefinitions.ts');
const flowDesignerApi = readText('../api/flowDesigner.ts');
const formDefinitionsApi = readText('../api/formDefinitions.ts');
const formStorageApi = readText('../api/formStorage.ts');
const approvalRulesApi = readText('../api/approvalRules.ts');
const todoFieldsApi = readText('../api/todoFields.ts');
const slaConfigApi = readText('../api/slaConfig.ts');
const workflowRuntimeApi = readText('../api/workflowRuntime.ts');
const notificationTemplateApi = readText('../api/notificationTemplate.ts');
const channelConfigApi = readText('../api/channelConfig.ts');
const mailGatewayApi = readText('../api/mailGateways.ts');
const mailTemplateApiSource = readText('../api/mailTemplate.ts');
const mailTemplateWrapperBlock = mailTemplateApiSource.slice(
  mailTemplateApiSource.indexOf('export const mailTemplateApi'),
  mailTemplateApiSource.indexOf('export const mailLogApi'),
);
const mailLogWrapperBlock = mailTemplateApiSource.slice(mailTemplateApiSource.indexOf('export const mailLogApi'));
const interfacesPage = readText('../pages/system/SystemInterfacesWorkbenchPage.tsx');
const fieldMappingsPage = readText('../pages/system/SystemFieldMappingsWorkbenchPage.tsx');
const syncRulesPage = readText('../pages/system/SystemSyncRulesWorkbenchPage.tsx');
const webhookConfigPage = readText('../pages/system/SystemWebhookConfigWorkbenchPage.tsx');
const externalSystemsPage = readText('../pages/system/SystemExternalSystemsWorkbenchPage.tsx');
const baseParamsPage = readText('../pages/system/SystemBaseParamsWorkbenchPage.tsx');
const securityPolicyPage = readText('../pages/system/SystemSecurityPolicyWorkbenchPage.tsx');
const auditLogPage = readText('../pages/system/SystemAuditLogWorkbenchPage.tsx');
const mailGatewayPage = readText('../pages/system/SystemMailGatewayWorkbenchPage.tsx');
const mailTemplatePage = readText('../pages/system/SystemMailTemplatesWorkbenchPage.tsx');
const mailLogPage = readText('../pages/system/SystemMailLogsWorkbenchPage.tsx');
const notificationTemplatePage = readText('../pages/system/SystemNotificationTemplatesWorkbenchPage.tsx');
const notificationChannelsPage = readText('../pages/system/SystemNotificationChannelsWorkbenchPage.tsx');
const notificationPreferencePage = readText('../pages/system/SystemNotificationPreferencesWorkbenchPage.tsx');
const notificationSwitchPage = readText('../pages/system/SystemWorkflowNotificationSwitchWorkbenchPage.tsx');
const cacheManagementPage = readText('../pages/system/SystemCacheManagementWorkbenchPage.tsx');
const fileStoragePage = readText('../pages/system/SystemFileStorageWorkbenchPage.tsx');
const assetCategoryPage = readText('../pages/system/SystemAssetCategoryWorkbenchPage.tsx');
const numberingRulesPage = readText('../pages/system/SystemNumberingRulesWorkbenchPage.tsx');
const customFieldPage = readText('../pages/system/SystemCustomFieldsWorkbenchPage.tsx');
const customFieldsetPage = readText('../pages/system/SystemCustomFieldSetsWorkbenchPage.tsx');
const vendorPage = readText('../pages/system/SystemVendorManagementWorkbenchPage.tsx');
const locationPage = readText('../pages/system/SystemLocationManagementWorkbenchPage.tsx');
const userPage = readText('../pages/system/SystemUserManagementWorkbenchPage.tsx');
const deptPage = readText('../pages/system/SystemDeptOrgWorkbenchPage.tsx');
const rolePermissionsPage = readText('../pages/system/SystemRolePermissionsWorkbenchPage.tsx');
const menuPermissionsPage = readText('../pages/system/SystemMenuPermissionsWorkbenchPage.tsx');
const postManagementPage = readText('../pages/system/SystemPostManagementWorkbenchPage.tsx');
const flowDefinitionPage = readText('../pages/system/SystemFlowDefinitionWorkbenchPage.tsx');
const flowDesignerPage = readText('../pages/system/SystemFlowDesignerWorkbenchPage.tsx');
const formConfigPage = readText('../pages/system/SystemFormConfigWorkbenchPage.tsx');
const formStoragePage = readText('../pages/system/SystemFormStorageWorkbenchPage.tsx');
const approvalRulesPage = readText('../pages/system/SystemApprovalRulesWorkbenchPage.tsx');
const todoFieldsPage = readText('../pages/system/SystemTodoFieldsWorkbenchPage.tsx');
const slaConfigPage = readText('../pages/system/SystemSlaConfigWorkbenchPage.tsx');
const runtimeMonitorPage = readText('../pages/system/SystemRuntimeMonitorWorkbenchPage.tsx');
const commandCenterPage = readText('../pages/system/SystemSettingsCommandCenterWorkbenchPage.tsx');

describe('V3 registry 与编号规则闭环边界', () => {
  it('registry 新增 system-numbering-rules 专属 V3 页面且仍非全量', () => {
    const registeredPageCount = (registrySource.match(/lazy\(\(\) => import\('\.\.\/\.\.\/system\//g) ?? []).length;
    expect(registrySource).toMatch(/^\s*'system-interfaces'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-field-mapping'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-sync-rules'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-webhook-config'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-external-systems'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-base-params'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-security-policy'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-audit-log'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-mail-gateway'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-mail-templates'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-mail-logs'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-notification-templates'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-notification-channels'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-notification-preferences'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-workflow-notification-switch'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-cache-management'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-file-storage'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-asset-category'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-numbering-rules'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-custom-fields'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-custom-field-sets'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-vendor-management'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-location-management'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-user-management'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-dept-org'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-role-permissions'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-menu-permissions'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-post-management'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-tenant-management'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-data-permissions'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-flow-definition'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-flow-designer'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-form-config'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-form-storage'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-approval-rules'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-todo-fields'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-sla-config'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-runtime-monitor'\s*:/m);
    expect(registrySource).toMatch(/^\s*'system-settings-command-center'\s*:/m);
    expect(registrySource).toContain("'system-webhook-config': lazy(() => import('../../system/SystemWebhookConfigWorkbenchPage'))");
    expect(registrySource).toContain("'system-external-systems': lazy(() => import('../../system/SystemExternalSystemsWorkbenchPage'))");
    expect(registrySource).toContain("'system-base-params': lazy(() => import('../../system/SystemBaseParamsWorkbenchPage'))");
    expect(registrySource).toContain("'system-security-policy': lazy(() => import('../../system/SystemSecurityPolicyWorkbenchPage'))");
    expect(registrySource).toContain("'system-audit-log': lazy(() => import('../../system/SystemAuditLogWorkbenchPage'))");
    expect(registrySource).toContain("'system-mail-gateway': lazy(() => import('../../system/SystemMailGatewayWorkbenchPage'))");
    expect(registrySource).toContain("'system-mail-templates': lazy(() => import('../../system/SystemMailTemplatesWorkbenchPage'))");
    expect(registrySource).toContain("'system-mail-logs': lazy(() => import('../../system/SystemMailLogsWorkbenchPage'))");
    expect(registrySource).toContain("'system-notification-templates': lazy(() => import('../../system/SystemNotificationTemplatesWorkbenchPage'))");
    expect(registrySource).toContain("'system-notification-channels': lazy(() => import('../../system/SystemNotificationChannelsWorkbenchPage'))");
    expect(registrySource).toContain("'system-notification-preferences': lazy(() => import('../../system/SystemNotificationPreferencesWorkbenchPage'))");
    expect(registrySource).toContain("'system-workflow-notification-switch': lazy(() => import('../../system/SystemWorkflowNotificationSwitchWorkbenchPage'))");
    expect(registrySource).toContain("'system-cache-management': lazy(() => import('../../system/SystemCacheManagementWorkbenchPage'))");
    expect(registrySource).toContain("'system-file-storage': lazy(() => import('../../system/SystemFileStorageWorkbenchPage'))");
    expect(registrySource).toContain("'system-asset-category': lazy(() => import('../../system/SystemAssetCategoryWorkbenchPage'))");
    expect(registrySource).toContain("'system-numbering-rules': lazy(() => import('../../system/SystemNumberingRulesWorkbenchPage'))");
    expect(registrySource).toContain("'system-custom-fields': lazy(() => import('../../system/SystemCustomFieldsWorkbenchPage'))");
    expect(registrySource).toContain("'system-custom-field-sets': lazy(() => import('../../system/SystemCustomFieldSetsWorkbenchPage'))");
    expect(registrySource).toContain("'system-vendor-management': lazy(() => import('../../system/SystemVendorManagementWorkbenchPage'))");
    expect(registrySource).toContain("'system-location-management': lazy(() => import('../../system/SystemLocationManagementWorkbenchPage'))");
    expect(registrySource).toContain("'system-user-management': lazy(() => import('../../system/SystemUserManagementWorkbenchPage'))");
    expect(registrySource).toContain("'system-dept-org': lazy(() => import('../../system/SystemDeptOrgWorkbenchPage'))");
    expect(registrySource).toContain("'system-role-permissions': lazy(() => import('../../system/SystemRolePermissionsWorkbenchPage'))");
    expect(registrySource).toContain("'system-menu-permissions': lazy(() => import('../../system/SystemMenuPermissionsWorkbenchPage'))");
    expect(registrySource).toContain("'system-post-management': lazy(() => import('../../system/SystemPostManagementWorkbenchPage'))");
    expect(registrySource).toContain("'system-tenant-management': lazy(() => import('../../system/SystemTenantManagementWorkbenchPage'))");
    expect(registrySource).toContain("'system-data-permissions': lazy(() => import('../../system/SystemDataPermissionsWorkbenchPage'))");
    expect(registrySource).toContain("'system-flow-definition': lazy(() => import('../../system/SystemFlowDefinitionWorkbenchPage'))");
    expect(registrySource).toContain("'system-flow-designer': lazy(() => import('../../system/SystemFlowDesignerWorkbenchPage'))");
    expect(registrySource).toContain("'system-form-config': lazy(() => import('../../system/SystemFormConfigWorkbenchPage'))");
    expect(registrySource).toContain("'system-form-storage': lazy(() => import('../../system/SystemFormStorageWorkbenchPage'))");
    expect(registrySource).toContain("'system-approval-rules': lazy(() => import('../../system/SystemApprovalRulesWorkbenchPage'))");
    expect(registrySource).toContain("'system-todo-fields': lazy(() => import('../../system/SystemTodoFieldsWorkbenchPage'))");
    expect(registrySource).toContain("'system-sla-config': lazy(() => import('../../system/SystemSlaConfigWorkbenchPage'))");
    expect(registrySource).toContain("'system-runtime-monitor': lazy(() => import('../../system/SystemRuntimeMonitorWorkbenchPage'))");
    expect(registrySource).toContain("'system-settings-command-center': lazy(() => import('../../system/SystemSettingsCommandCenterWorkbenchPage'))");
    expect(registeredPageCount).toBe(39);
    expect(registeredPageCount).not.toBe(44);
    expect(registrySource).not.toContain('IntegrationConfigWorkbenchPage');
  });

  it('module registry 三十九项均指向 workbenchv3 且仍非全量', () => {
    const registeredMenuCount = (moduleSource.match(/menuId: SYSTEM_/g) ?? []).length;
    for (const menuId of ['system-interfaces', 'system-field-mapping', 'system-sync-rules', 'system-webhook-config', 'system-external-systems', 'system-base-params', 'system-security-policy', 'system-audit-log', 'system-mail-gateway', 'system-mail-templates', 'system-mail-logs', 'system-notification-templates', 'system-notification-channels', 'system-notification-preferences', 'system-workflow-notification-switch', 'system-cache-management', 'system-file-storage', 'system-asset-category', 'system-numbering-rules', 'system-custom-fields', 'system-custom-field-sets', 'system-vendor-management', 'system-location-management', 'system-user-management', 'system-dept-org', 'system-role-permissions', 'system-menu-permissions', 'system-post-management', 'system-tenant-management', 'system-data-permissions', 'system-flow-definition', 'system-flow-designer', 'system-form-config', 'system-form-storage', 'system-approval-rules', 'system-todo-fields', 'system-sla-config', 'system-runtime-monitor', 'system-settings-command-center']) {
      expect(moduleSource).toContain(`workbenchPath: '/fixed-assets/workbenchv3?menu=${menuId}'`);
      expect(moduleSource).toContain(`legacyRoute: '/fixed-assets/workbenchv3?menu=${menuId}'`);
    }
    expect(registeredMenuCount).toBe(39);
    expect(registeredMenuCount).not.toBe(44);
    expect(moduleSource).toContain('SYSTEM_SECURITY_POLICY_MODULE');
    expect(moduleSource).toContain('SYSTEM_AUDIT_LOG_MODULE');
    expect(moduleSource).toContain('SYSTEM_MAIL_GATEWAY_MODULE');
    expect(moduleSource).toContain('SYSTEM_MAIL_TEMPLATES_MODULE');
    expect(moduleSource).toContain('SYSTEM_MAIL_LOGS_MODULE');
    expect(moduleSource).toContain('SYSTEM_NOTIFICATION_TEMPLATES_MODULE');
    expect(moduleSource).toContain('SYSTEM_NOTIFICATION_CHANNELS_MODULE');
    expect(moduleSource).toContain('SYSTEM_NOTIFICATION_PREFERENCES_MODULE');
    expect(moduleSource).toContain('SYSTEM_WORKFLOW_NOTIFICATION_SWITCH_MODULE');
    expect(moduleSource).toContain('SYSTEM_NUMBERING_RULES_MODULE');
    expect(moduleSource).toContain('SYSTEM_CUSTOM_FIELDS_MODULE');
    expect(moduleSource).toContain('SYSTEM_CUSTOM_FIELD_SETS_MODULE');
    expect(moduleSource).toContain('SYSTEM_MENU_PERMISSIONS_MODULE');
  });

  it('wrapper 只包含各自后端契约', () => {
    expect(interfacesApi).toContain("'/system/interfaces'");
    expect(interfacesApi).toContain('`${SYSTEM_INTERFACES_BASE}/${id}/test`');
    expect(interfacesApi).not.toContain("'/system/field-mappings'");
    expect(interfacesApi).not.toContain("'/system/sync-rules'");

    expect(fieldMappingsApi).toContain("'/system/field-mappings'");
    expect(fieldMappingsApi).toContain('`${SYSTEM_FIELD_MAPPINGS_BASE}/preview`');
    expect(fieldMappingsApi).not.toContain("'/system/sync-rules'");

    expect(syncRulesApi).toContain("'/system/sync-rules'");
    expect(syncRulesApi).toContain('`${SYSTEM_SYNC_RULES_BASE}/${id}/dry-run`');
    expect(syncRulesApi).toContain('`${SYSTEM_SYNC_RULES_BASE}/queue/summary`');
    expect(syncRulesApi).not.toMatch(/retry-due|scan-due|consume/);

    expect(webhookConfigsApi).toContain("'/system/webhook-configs'");
    expect(webhookConfigsApi).toContain('`${SYSTEM_WEBHOOK_CONFIGS_BASE}/${id}/test`');
    expect(webhookConfigsApi).not.toContain('/settings');
    expect(webhookConfigsApi).not.toMatch(/sendWebhook|dispatchWebhook|systemIntegration/);

    expect(externalSystemsApi).toContain("'/system/external-systems'");
    expect(externalSystemsApi).toContain('`${SYSTEM_EXTERNAL_SYSTEMS_BASE}/${id}/enable`');
    expect(externalSystemsApi).toContain('`${SYSTEM_EXTERNAL_SYSTEMS_BASE}/${id}/disable`');
    expect(externalSystemsApi).toContain('`${SYSTEM_EXTERNAL_SYSTEMS_BASE}/${id}/validate`');
    expect(externalSystemsApi).not.toContain("'../api/workflow'");
    expect(externalSystemsApi).not.toMatch(/webhook-configs|interfaces|settings|public\/mock|fixed-assets\/workbench\?menu=/);

    expect(systemConfigApi).toContain("'/system-config/system'");
    expect(systemConfigApi).toContain("'/system/configs'");
    expect(systemConfigApi).toContain("'/system-config/system/preview'");
    expect(systemConfigApi).toContain("'/system-config/security'");
    expect(systemConfigApi).toContain("'/system-config/security/preview'");
    expect(systemConfigApi).toContain('previewSecurityConfig');
    expect(systemConfigApi).toContain('runtimeEffect: boolean');
    expect(systemConfigApi).toContain("'/system/configs/refresh-cache'");
    expect(systemConfigApi).toContain('SystemConfigRefreshResult');
    expect(systemConfigApi).not.toContain("'../api/workflow'");
    expect(systemConfigApi).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=/);

    expect(auditApi).toContain("'/audit-logs'");
    expect(auditApi).toContain("'/audit-logs/stats'");
    expect(auditApi).toContain("'/audit-logs/trends'");
    expect(auditApi).toContain("'/audit-logs/action-type-distribution'");
    expect(auditApi).toContain("'/audit-logs/operator-ranking'");
    expect(auditApi).toContain("'/audit-logs/meta'");
    expect(auditApi).not.toMatch(/http\.(post|put|delete|patch)|Blob|createObjectURL|downloadUrl/);
    expect(auditApi).not.toContain("'../api/workflow'");

    expect(notificationTemplateApi).toContain("'/notification-templates/list'");
    expect(notificationTemplateApi).toContain('`/notification-templates/${id}`');
    expect(notificationTemplateApi).toContain('`/notification-templates/code/${code}`');
    expect(notificationTemplateApi).toContain("'/notification-templates/meta'");
    expect(notificationTemplateApi).toContain("'/notification-templates/preview'");
    expect(notificationTemplateApi).toContain('notificationPreferenceApi');
    expect(notificationTemplateApi).toContain('notificationSwitchApi');
    expect(notificationTemplateApi).toContain("'/notification-preferences/meta'");
    expect(notificationTemplateApi).toContain("'/notification-preferences/preview'");
    expect(notificationTemplateApi).toContain("'/notification-switches/list'");
    expect(notificationTemplateApi).toContain('`/notification-switches/biz-type/${bizType}`');
    expect(notificationTemplateApi).toContain("'/notification-switches/meta'");
    expect(notificationTemplateApi).toContain("'/notification-switches/preview'");
    expect(notificationTemplateApi).toContain('`/notification-switches/${id}`');
    expect(notificationTemplateApi).not.toMatch(/send|test-send|queue|websocket|webhook|mail-gateway/);

    expect(channelConfigApi).toContain("'/system/channel-configs'");
    expect(channelConfigApi).toContain('`/system/channel-configs/${id}`');
    expect(channelConfigApi).toContain("'/system/channel-configs/meta'");
    expect(channelConfigApi).toContain("'/system/channel-configs/preview'");
    expect(channelConfigApi).toContain("'/system/channel-configs'");
    expect(channelConfigApi).toContain('`/system/channel-configs/${channelType}/test`');

    expect(mailGatewayApi).toContain("'/system/mail-gateways'");
    expect(mailGatewayApi).toContain('`/system/mail-gateways/${id}`');
    expect(mailGatewayApi).toContain("'/system/mail-gateways/meta'");
    expect(mailGatewayApi).toContain("'/system/mail-gateways/preview'");
    expect(mailGatewayApi).not.toMatch(/create\(|update\(|delete\(|save\(|testConnection|\/test`|\/test'|send\(|retry\(|workflowApi|channelConfigApi|systemConfig|mailTemplateApi|mailLogApi|notificationTemplateApi|notificationPreferenceApi|notificationSwitchApi|routePermissions|auth\/login\/mobile/);

    expect(mailTemplateWrapperBlock).toContain("'/mail-templates/list'");
    expect(mailTemplateWrapperBlock).toContain('`/mail-templates/${id}`');
    expect(mailTemplateWrapperBlock).toContain('`/mail-templates/code/${code}`');
    expect(mailTemplateWrapperBlock).toContain("'/mail-templates/meta'");
    expect(mailTemplateWrapperBlock).toContain("'/mail-templates/preview'");
    expect(mailTemplateWrapperBlock).toContain("'/mail-templates'");
    expect(mailTemplateWrapperBlock).toContain('`/mail-templates/${id}`');
    expect(mailTemplateWrapperBlock).not.toMatch(/mailLogApi|test-send|queue|websocket|webhook|mail-gateway|workflow|notification/);

    expect(mailLogWrapperBlock).toContain("'/mail-logs/list'");
    expect(mailLogWrapperBlock).toContain('`/mail-logs/${id}`');
    expect(mailLogWrapperBlock).toContain("'/mail-logs/biz'");
    expect(mailLogWrapperBlock).toContain("'/mail-logs/meta'");
    expect(mailLogWrapperBlock).toContain('`/mail-logs/${id}/retry`');
    expect(mailLogWrapperBlock).not.toMatch(/mail-logs\/export|download|test-send|queue|websocket|webhook|mail-gateway|workflow|notificationTemplateApi|mailTemplateApi\.(create|update|delete|preview)/);

    expect(cacheManagementApi).toContain("'/system/cache/namespaces'");
    expect(cacheManagementApi).toContain('`${SYSTEM_CACHE_NAMESPACES_BASE}/${encodeURIComponent(namespace)}/refresh`');
    expect(cacheManagementApi).toContain("'/system/cache/refresh'");
    expect(cacheManagementApi).not.toContain('/settings');
    expect(cacheManagementApi).not.toMatch(/mock|iframe/);

    expect(fileStorageApi).toContain("'/system/file-storage/attachments/catalog'");
    expect(fileStorageApi).not.toMatch(/api\.(post|put|delete|patch)/);
    expect(fileStorageApi).not.toMatch(/FormData|Blob|createObjectURL|downloadUrl|previewUrl|storagePath/);

    expect(assetCategoriesApi).toContain("'/categories/list'");
    expect(assetCategoriesApi).toContain("'/categories/tree'");
    expect(assetCategoriesApi).not.toContain('/api/v1/asset-categories');
    expect(assetCategoriesApi).not.toContain('../services/categoryService');

    expect(numberingRulesApi).toContain("'/numbering-rules'");
    expect(numberingRulesApi).toContain('`/numbering-rules/${encodeURIComponent(ruleKey)}`');
    expect(numberingRulesApi).toContain("'/numbering-rules/meta'");
    expect(numberingRulesApi).toContain("'/numbering-rules/preview'");
    expect(numberingRulesApi).not.toMatch(/systemConfig|system\/configs|createSysConfig|updateSysConfig|deleteSysConfig|saveSystemConfig|refreshSysConfigCache|workflowApi|@\/api\/workflow|routePermissions|auth\/login\/mobile/);

    expect(customFieldApi).toContain("'/system/custom-fields'");
    expect(customFieldApi).toContain("'/system/custom-fields/all'");
    expect(customFieldApi).toContain('`/system/custom-fields/${id}`');
    expect(customFieldApi).toContain("'/system/custom-fields/meta'");
    expect(customFieldApi).toContain("'/system/custom-fields/preview'");
    expect(customFieldApi).toContain("'/system/custom-fieldsets'");
    expect(customFieldApi).toContain("'/system/custom-fieldsets/meta'");
    expect(customFieldApi).toContain("'/system/custom-fieldsets/preview'");
    expect(customFieldApi).toContain('`/assets/${assetId}/custom-fields`');

    expect(vendorsApi).toContain("'/vendors/list'");
    expect(vendorsApi).not.toMatch(/api\.post|api\.put|api\.delete/);
    expect(locationsApi).toContain("'/locations/list'");
    expect(locationsApi).toContain("'/locations/root'");
    expect(locationsApi).not.toMatch(/api\.post|api\.put|api\.delete/);

    expect(userManagementApi).toContain("'/user-management/list'");
    expect(userManagementApi).not.toMatch(/api\.post|api\.put|api\.delete/);
    expect(userManagementApi).not.toMatch(new RegExp('pass' + 'word', 'i'));
    expect(deptsApi).toContain("'/depts/list'");
    expect(deptsApi).toContain("'/depts/tree'");
    expect(deptsApi).not.toMatch(/api\.post|api\.put|api\.delete/);

    expect(rolePermissionsApi).toContain("'/system/role-permissions/catalog'");
    expect(rolePermissionsApi).not.toMatch(/api\.post|api\.put|api\.delete|api\.patch/);
    expect(rolePermissionsApi).not.toContain("'/roles/list'");

    expect(workflowDefinitionsApi).toContain("'/workflows'");
    expect(workflowDefinitionsApi).toContain('`${WORKFLOW_DEFINITIONS_BASE}/${encodeURIComponent(businessType)}`');
    expect(workflowDefinitionsApi).not.toMatch(/api\.post|api\.put|api\.delete/);
    expect(workflowDefinitionsApi).not.toMatch(/\/draft|\/publish|\/status/);

    expect(flowDesignerApi).toContain("'/workflows'");
    expect(flowDesignerApi).toContain("'/designer/draft'");
    expect(flowDesignerApi).toContain("'/designer/validate'");
    expect(flowDesignerApi).toContain("'/publish'");
    expect(flowDesignerApi).toContain('`/versions/${version}/rollback`');

    expect(formDefinitionsApi).toContain("'/form-definitions'");
    expect(formDefinitionsApi).toContain("'/schema/validate'");
    expect(formDefinitionsApi).toContain("'/publish'");
    expect(formDefinitionsApi).toContain("'/disable'");
    expect(formDefinitionsApi).toContain("'/preview'");
    expect(formDefinitionsApi).toContain("'/references'");
    expect(formDefinitionsApi).toContain('`/versions/${encodeURIComponent(String(version))}/rollback`');
    expect(formDefinitionsApi).not.toContain("'../api/workflow'");
    expect(formDefinitionsApi).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=/);

    expect(formStorageApi).toContain("'/form-storage'");
    expect(formStorageApi).toContain("'/attachments'");
    expect(formStorageApi).toContain("'/archive'");
    expect(formStorageApi).toContain('`${FORM_STORAGE_BASE}/export`');
    expect(formStorageApi).toContain('http.delete<FormStorageRecord>');
    expect(formStorageApi).toContain('http.delete<FormStorageAttachmentSummary>');
    expect(formStorageApi).not.toContain("'../api/workflow'");
    expect(formStorageApi).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=|FormData|Blob|createObjectURL/);

    expect(approvalRulesApi).toContain("'/approval-rules'");
    expect(approvalRulesApi).toContain("'/enable'");
    expect(approvalRulesApi).toContain("'/disable'");
    expect(approvalRulesApi).toContain('`${APPROVAL_RULES_BASE}/simulate`');
    expect(approvalRulesApi).toContain('`${APPROVAL_RULES_BASE}/conflicts`');
    expect(approvalRulesApi).not.toContain("'../api/workflow'");
    expect(approvalRulesApi).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=/);

    expect(todoFieldsApi).toContain("'/todo-fields'");
    expect(todoFieldsApi).toContain('`${TODO_FIELDS_BASE}/sort-order`');
    expect(todoFieldsApi).toContain('`${TODO_FIELDS_BASE}/role-overrides/');
    expect(todoFieldsApi).toContain('`${TODO_FIELDS_BASE}/reset-defaults`');
    expect(todoFieldsApi).toContain('`${TODO_FIELDS_BASE}/preview`');
    expect(todoFieldsApi).not.toContain("'../api/workflow'");
    expect(todoFieldsApi).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=/);

    expect(slaConfigApi).toContain("'/sla-config'");
    expect(slaConfigApi).toContain("'/enable'");
    expect(slaConfigApi).toContain("'/disable'");
    expect(slaConfigApi).toContain('`${SLA_CONFIG_BASE}/simulate`');
    expect(slaConfigApi).toContain('`${SLA_CONFIG_BASE}/runtime-summary`');
    expect(slaConfigApi).toContain('`${SLA_CONFIG_BASE}/timeout-records`');
    expect(slaConfigApi).toContain('`${SLA_CONFIG_BASE}/export`');
    expect(slaConfigApi).not.toContain("'../api/workflow'");
    expect(slaConfigApi).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=/);

    expect(workflowRuntimeApi).toContain("'/approvals/list'");
    expect(workflowRuntimeApi).toContain("'/approvals/pending/count'");
    expect(workflowRuntimeApi).toContain("'/sla-config/runtime-summary'");
    expect(workflowRuntimeApi).toContain("'/sla-config/timeout-records'");
    expect(workflowRuntimeApi).not.toMatch(/api\.post|api\.put|api\.delete/);
    expect(workflowRuntimeApi).not.toMatch(/\/approvals\/\$\{id\}/);
  });

  it('页面体现 V3 安全边界', () => {
    expect(interfacesPage).toContain('未触发真实外部调用');
    expect(fieldMappingsPage).toContain('trim(value)、upper(value)、lower(value)');
    expect(syncRulesPage).toContain('dryRun 默认 true');
    expect(syncRulesPage).toContain('单条日志重试');
    expect(syncRulesPage).toContain('只读队列摘要');
    expect(webhookConfigPage).toContain('config-only');
    expect(webhookConfigPage).toContain('未触发真实外部调用');
    expect(webhookConfigPage).not.toContain('/settings');
    expect(externalSystemsPage).toContain('真实调用 /system/external-systems');
    expect(externalSystemsPage).toContain('config-only');
    expect(externalSystemsPage).toContain('未触发真实外部调用');
    expect(externalSystemsPage).toContain('认证材料仅保存脱敏摘要');
    expect(externalSystemsPage).toContain('confirmed: true');
    expect(externalSystemsPage).not.toMatch(/public\/mock|fixed-assets\/workbench\?menu=/);
    expect(baseParamsPage).toContain('真实调用 /system-config/system 与 /system/configs');
    expect(baseParamsPage).toContain('影响预演');
    expect(baseParamsPage).toContain('缓存刷新结果');
    expect(baseParamsPage).toContain('DEGRADED');
    expect(baseParamsPage).toContain('未写库、未刷新缓存、未改变业务状态');
    expect(baseParamsPage).toContain('data-system-base-params="workbench-v3"');
    expect(baseParamsPage).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=|SystemSecurityPolicyWorkbenchPage/);
    expect(securityPolicyPage).toContain('真实调用 /system-config/security 与 /system-config/security/preview');
    expect(securityPolicyPage).toContain('configuration-state');
    expect(securityPolicyPage).toContain('preview-state');
    expect(securityPolicyPage).toContain('runtimeEffect=false');
    expect(securityPolicyPage).toContain('no-login-chain / no-direct-effect');
    expect(securityPolicyPage).toContain('data-system-security-policy="workbench-v3"');
    expect(securityPolicyPage).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=|routePermissions|auth\/login\/mobile/);
    expect(auditLogPage).toContain('真实调用 /audit-logs');
    expect(auditLogPage).toContain('/audit-logs/action-type-distribution');
    expect(auditLogPage).toContain('/audit-logs/operator-ranking');
    expect(auditLogPage).toContain('GET-only / tenant-scoped / masked');
    expect(auditLogPage).toContain('不代表全模块审计覆盖');
    expect(auditLogPage).toContain('不可篡改合规归档或 SIEM');
    expect(auditLogPage).toContain('导出能力仅展示脱敏快照与限制说明');
    expect(auditLogPage).toContain('data-system-audit-log="workbench-v3"');
    expect(auditLogPage).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=|createObjectURL|downloadUrl|routePermissions|auth\/login\/mobile/);
    expect(mailGatewayPage).toContain('真实调用 /system/mail-gateways');
    expect(mailGatewayPage).toContain('/system/mail-gateways/{id}');
    expect(mailGatewayPage).toContain('/system/mail-gateways/meta');
    expect(mailGatewayPage).toContain('/system/mail-gateways/preview');
    expect(mailGatewayPage).toContain('metadata-only catalog');
    expect(mailGatewayPage).toContain('noPersistence=true、noSend=true、noNetwork=true');
    expect(mailGatewayPage).toContain('不代表消息与通知组、邮件子系统或 Workbench V3 全量完成');
    expect(mailGatewayPage).toContain('data-system-mail-gateway="workbench-v3"');
    expect(mailGatewayPage).toContain('mailGatewayApi.list');
    expect(mailGatewayPage).toContain('mailGatewayApi.getById');
    expect(mailGatewayPage).toContain('mailGatewayApi.meta');
    expect(mailGatewayPage).toContain('mailGatewayApi.preview');
    expect(mailGatewayPage).not.toMatch(/channelConfigApi|systemConfig|mailTemplateApi|mailLogApi|notificationTemplateApi|notificationPreferenceApi|notificationSwitchApi|workflowApi|@\/api\/workflow|\.\.\/api\/workflow|routePermissions|auth\/login\/mobile|保存修改|删除|测试连接|发送邮件|重试/);
    expect(notificationTemplatePage).toContain('真实调用 /notification-templates/list');
    expect(notificationTemplatePage).toContain('/notification-templates/preview');
    expect(notificationTemplatePage).toContain('无持久化 safe preview');
    expect(notificationTemplatePage).toContain('missingVariables');
    expect(notificationTemplatePage).toContain('rejectedVariables');
    expect(notificationTemplatePage).toContain('nonPersistent=true');
    expect(notificationTemplatePage).toContain('不发送通知、不配置渠道、不修改偏好、不控制流程通知开关、不接入邮件网关');
    expect(notificationTemplatePage).toContain('data-system-notification-templates="workbench-v3"');
    expect(notificationTemplatePage).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=|notificationPreferenceApi|notificationSwitchApi|mail|send APIs|queue|websocket|webhook/);
    expect(notificationChannelsPage).toContain('真实调用 /system/channel-configs');
    expect(notificationChannelsPage).toContain('/system/channel-configs/{id}');
    expect(notificationChannelsPage).toContain('/system/channel-configs/meta');
    expect(notificationChannelsPage).toContain('/system/channel-configs/preview');
    expect(notificationChannelsPage).toContain('只读通知渠道目录 + 无持久化、无发送、无外联脱敏预览');
    expect(notificationChannelsPage).toContain('configured、webhookUrlMasked、webhookUrlConfigured、signatureConfigured、sampleEndpointAccepted、rejectedInputs、tenantScoped、noPersistence、noSend 与 runtimeEffect=false');
    expect(notificationChannelsPage).toContain('消息与通知组未全组完成');
    expect(notificationChannelsPage).toContain('仍非 44/44');
    expect(notificationChannelsPage).toContain('data-system-notification-channels="workbench-v3"');
    expect(notificationChannelsPage).toContain('channelConfigApi.list');
    expect(notificationChannelsPage).toContain('channelConfigApi.getById');
    expect(notificationChannelsPage).toContain('channelConfigApi.meta');
    expect(notificationChannelsPage).toContain('channelConfigApi.preview');
    expect(notificationChannelsPage).not.toMatch(/channelConfigApi\.(create|update|delete|test)|NotificationChannelTab|notificationPreferenceApi|notificationSwitchApi|notificationTemplateApi\.(create|update|delete)|mailTemplateApi|mailLogApi|mailGatewayApi|\.\.\/api\/workflow|routePermissions|auth\/login\/mobile|queue|websocket|providerRequest/);
    expect(notificationPreferencePage).toContain('真实调用 /notification-preferences');
    expect(notificationPreferencePage).toContain('/notification-preferences/{category}');
    expect(notificationPreferencePage).toContain('/notification-preferences/meta');
    expect(notificationPreferencePage).toContain('/notification-preferences/preview');
    expect(notificationPreferencePage).toContain('只读通知偏好目录 + 无持久化偏好决策预览');
    expect(notificationPreferencePage).toContain('wouldReceive、inAppEnabled、emailEnabled、quietWindowMatched、missingPreferences、rejectedInputs、tenantScoped、noPersistence 与 runtimeEffect=false');
    expect(notificationPreferencePage).toContain('消息与通知组未全组完成');
    expect(notificationPreferencePage).toContain('仍非 44/44');
    expect(notificationPreferencePage).toContain('data-system-notification-preferences="workbench-v3"');
    expect(notificationPreferencePage).toContain('notificationPreferenceApi.list');
    expect(notificationPreferencePage).toContain('notificationPreferenceApi.getByCategory');
    expect(notificationPreferencePage).toContain('notificationPreferenceApi.meta');
    expect(notificationPreferencePage).toContain('notificationPreferenceApi.preview');
    expect(notificationPreferencePage).not.toMatch(/notificationPreferenceApi\.save|notificationPreferenceApi\.batchSave|notificationSwitchApi|notificationTemplateApi\.(create|update|delete)|channelConfigApi|mailTemplateApi|mailLogApi|mailGatewayApi|\.\.\/api\/workflow|routePermissions|auth\/login\/mobile|queue|websocket|webhook/);
    expect(notificationSwitchPage).toContain('真实调用 /notification-switches/list');
    expect(notificationSwitchPage).toContain('/notification-switches/biz-type/{bizType}');
    expect(notificationSwitchPage).toContain('/notification-switches/meta');
    expect(notificationSwitchPage).toContain('/notification-switches/preview');
    expect(notificationSwitchPage).toContain('read-only notification switch catalog + no-persistence preview + no-send preview');
    expect(notificationSwitchPage).toContain('wouldNotify、blockedBySwitch、matchedSwitches、missingSwitches、rejectedInputs、tenantScoped、noPersistence、noSend、workflowRuntimeEffect=false');
    expect(notificationSwitchPage).toContain('not flow-platform acceptance');
    expect(notificationSwitchPage).toContain('not message-notification group completion');
    expect(notificationSwitchPage).toContain('not Workbench V3 full completion');
    expect(notificationSwitchPage).toContain('消息与通知组未全组完成');
    expect(notificationSwitchPage).toContain('仍非 44/44');
    expect(notificationSwitchPage).toContain('data-system-workflow-notification-switch="workbench-v3"');
    expect(notificationSwitchPage).toContain('notificationSwitchApi.list');
    expect(notificationSwitchPage).toContain('notificationSwitchApi.getByBizType');
    expect(notificationSwitchPage).toContain('notificationSwitchApi.meta');
    expect(notificationSwitchPage).toContain('notificationSwitchApi.preview');
    expect(notificationSwitchPage).not.toMatch(/notificationSwitchApi\.updateEnabled|notificationTemplateApi\.(create|update|delete)|notificationPreferenceApi\.(save|batchSave)|channelConfigApi|mailTemplateApi|mailLogApi|mailGatewayApi|\.\.\/api\/workflow|routePermissions|auth\/login\/mobile|messageCenter|eventPublisher|queue|websocket|webhook|push|retry/);
    expect(mailTemplatePage).toContain('真实调用 /mail-templates/list');
    expect(mailTemplatePage).toContain('/mail-templates/preview');
    expect(mailTemplatePage).toContain('无持久化 safe preview');
    expect(mailTemplatePage).toContain('missingVariables');
    expect(mailTemplatePage).toContain('rejectedVariables');
    expect(mailTemplatePage).toContain('renderedSubject');
    expect(mailTemplatePage).toContain('nonPersistent=true');
    expect(mailTemplatePage).toContain('不发送邮件、不配置 SMTP/邮件网关、不处理邮件日志/重试/导出、不接入流程邮件');
    expect(mailTemplatePage).toContain('data-system-mail-templates="workbench-v3"');
    expect(mailTemplatePage).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=|mailLogApi|notificationTemplateApi|notificationPreferenceApi|notificationSwitchApi|mailTemplateApi\.(create|update|delete)|queue|websocket|webhook/);
    expect(mailLogPage).toContain('真实调用 /mail-logs/list');
    expect(mailLogPage).toContain('/mail-logs/{id}');
    expect(mailLogPage).toContain('/mail-logs/biz');
    expect(mailLogPage).toContain('/mail-logs/meta');
    expect(mailLogPage).toContain('redacted=true');
    expect(mailLogPage).toContain('tenantScoped=true');
    expect(mailLogPage).toContain('no retry/export/send');
    expect(mailLogPage).toContain('不保证日志采集链路');
    expect(mailLogPage).toContain('不代表邮件子系统完成');
    expect(mailLogPage).toContain('data-system-mail-logs="workbench-v3"');
    expect(mailLogPage).toContain('mailLogApi.list');
    expect(mailLogPage).toContain('mailLogApi.getById');
    expect(mailLogPage).toContain('mailLogApi.getByBiz');
    expect(mailLogPage).toContain('mailLogApi.meta');
    expect(mailLogPage).not.toMatch(/mailLogApi\.retry|mailTemplateApi|createObjectURL|downloadUrl|api\.post|api\.put|api\.delete|queue|websocket|webhook|notificationTemplateApi|notificationPreferenceApi|notificationSwitchApi/);
    expect(cacheManagementPage).toContain('空缓存');
    expect(cacheManagementPage).toContain('刷新全部白名单命名空间');
    expect(cacheManagementPage).not.toMatch(/iframe|public\/mock/);
    expect(fileStoragePage).toContain('只读展示 /system/file-storage/attachments/catalog');
    expect(fileStoragePage).toContain('附件元数据目录');
    expect(fileStoragePage).toContain('不支持上传/下载/预览/删除，不访问文件系统，不代表文件生命周期闭环');
    expect(fileStoragePage).toContain('敏感细节已脱敏');
    expect(fileStoragePage).not.toMatch(/iframe|public\/mock/);
    expect(assetCategoryPage).toContain('只读展示分类列表与分类树');
    expect(assetCategoryPage).toContain('重新加载');
    expect(assetCategoryPage).toContain('敏感细节已脱敏');
    expect(assetCategoryPage).not.toMatch(/iframe|public\/mock/);
    expect(numberingRulesPage).toContain('真实调用 /numbering-rules');
    expect(numberingRulesPage).toContain('/numbering-rules/{ruleKey}');
    expect(numberingRulesPage).toContain('/numbering-rules/meta');
    expect(numberingRulesPage).toContain('/numbering-rules/preview');
    expect(numberingRulesPage).toContain('read-only numbering rule catalog + no-persistence deterministic preview');
    expect(numberingRulesPage).toContain('previewValue、usedVariables、missingVariables、rejectedVariables、authority、warnings、tenantScoped、noPersistence、noSequenceReserved、runtimeEffect=false、cacheRefreshed=false、sequenceAllocated=false、persistent=false');
    expect(numberingRulesPage).toContain('当前不保证并发唯一');
    expect(numberingRulesPage).toContain('未接入资产/工单/流程创建链路');
    expect(numberingRulesPage).toContain('不代表基础资料组完成');
    expect(numberingRulesPage).toContain('不代表 44/44 或 Workbench V3 全量完成');
    expect(numberingRulesPage).toContain('data-system-numbering-rules="workbench-v3"');
    expect(numberingRulesPage).toContain('numberingRulesApi.list');
    expect(numberingRulesPage).toContain('numberingRulesApi.detail');
    expect(numberingRulesPage).toContain('numberingRulesApi.meta');
    expect(numberingRulesPage).toContain('numberingRulesApi.preview');
    expect(numberingRulesPage).not.toMatch(/workflowApi|\.\.\/api\/workflow|@\/api\/workflow|createSysConfig|updateSysConfig|deleteSysConfig|saveSystemConfig|refreshSysConfigCache|routePermissions|auth\/login\/mobile|新增规则|保存修改|删除规则|立即生效/);
    expect(customFieldPage).toContain('真实调用 /system/custom-fields');
    expect(customFieldPage).toContain('/system/custom-fields/preview');
    expect(customFieldPage).toContain('只读自定义字段定义目录 + 无持久化校验预览');
    expect(customFieldPage).toContain('valid、missing、rejected、errors、usedFields、tenantScoped、noPersistence 与 runtimeEffect=false');
    expect(customFieldPage).toContain('不代表字段集完成');
    expect(customFieldPage).toContain('不代表基础资料组完成');
    expect(customFieldPage).toContain('data-system-custom-fields="workbench-v3"');
    expect(customFieldPage).not.toMatch(/dangerouslySetInnerHTML|iframe|public\/mock|fixed-assets\/workbench\?menu=|createCustomField|updateCustomField|deleteCustomField|CustomFieldset|assignFieldsToFieldset|assignFieldsetToCategory|getAssetCustomFields|saveAssetCustomFields|routePermissions|auth\/login\/mobile|workflow/);
    expect(customFieldsetPage).toContain('真实调用 /system/custom-fieldsets');
    expect(customFieldsetPage).toContain('/system/custom-fieldsets/{id}/fields');
    expect(customFieldsetPage).toContain('/system/custom-fieldsets/by-category/{categoryId}');
    expect(customFieldsetPage).toContain('/system/custom-fieldsets/preview');
    expect(customFieldsetPage).toContain('只读字段集目录 + 无持久化字段分配/分类绑定预览');
    expect(customFieldsetPage).toContain('missingFields、rejectedFields、usedFields、wouldBindCategory、tenantScoped、noPersistence、runtimeEffect=false');
    expect(customFieldsetPage).toContain('基础资料组未全组完成');
    expect(customFieldsetPage).toContain('未覆盖全部 44 项');
    expect(customFieldsetPage).toContain('data-system-custom-field-sets="workbench-v3"');
    expect(customFieldsetPage).not.toMatch(/dangerouslySetInnerHTML|iframe|public\/mock|fixed-assets\/workbench\?menu=|createCustomFieldset|updateCustomFieldset|deleteCustomFieldset|assignFieldsToFieldset|assignFieldsetToCategory|getAssetCustomFields|saveAssetCustomFields|createCustomField|updateCustomField|deleteCustomField|routePermissions|auth\/login\/mobile|\.\.\/api\/workflow/);
    expect(vendorPage).toContain('只读展示 /vendors/list');
    expect(vendorPage).toContain('状态筛选');
    expect(vendorPage).toContain('敏感细节已脱敏');
    expect(vendorPage).not.toMatch(/iframe|public\/mock/);
    expect(locationPage).toContain('只读展示 /locations/list 与 /locations/root');
    expect(locationPage).toContain('根位置摘要');
    expect(locationPage).toContain('敏感细节已脱敏');
    expect(locationPage).not.toMatch(/iframe|public\/mock/);
    expect(userPage).toContain('只读展示 /user-management/list');
    expect(userPage).toContain('状态筛选');
    expect(userPage).toContain('敏感细节已脱敏');
    expect(userPage).not.toMatch(new RegExp('pass' + 'word', 'i'));
    expect(userPage).not.toMatch(/iframe|public\/mock/);
    expect(deptPage).toContain('只读展示 /depts/list 与 /depts/tree');
    expect(deptPage).toContain('根部门摘要');
    expect(deptPage).toContain('敏感细节已脱敏');
    expect(deptPage).not.toMatch(/iframe|public\/mock/);
    expect(rolePermissionsPage).toContain('只读展示 /system/role-permissions/catalog');
    expect(rolePermissionsPage).toContain('角色-权限绑定目录');
    expect(rolePermissionsPage).toContain('权限库存与绑定数量');
    expect(rolePermissionsPage).toContain('不支持分配/编辑/删除，不代表菜单权限或数据权限闭环');
    expect(rolePermissionsPage).toContain('敏感细节已脱敏');
    expect(rolePermissionsPage).not.toMatch(/iframe|public\/mock/);
    expect(menuPermissionsPage).toContain('只读展示 /system/role-permissions/catalog 的权限编码库存');
    expect(menuPermissionsPage).toContain('菜单权限只读目录');
    expect(menuPermissionsPage).toContain('当前后端未提供 sys_menu/菜单分配接口');
    expect(menuPermissionsPage).toContain('data-system-menu-permissions="workbench-v3"');
    expect(menuPermissionsPage).toContain('敏感细节已脱敏');
    expect(menuPermissionsPage).not.toMatch(/iframe|public\/mock|api\.(post|put|delete|patch)|createMenu|updateMenu|deleteMenu|assignMenu/);
    expect(postManagementPage).toContain('真实调用 /system/posts');
    expect(postManagementPage).toContain('/system/posts/all');
    expect(postManagementPage).toContain('/system/posts/{id}');
    expect(postManagementPage).toContain('/system/posts/meta');
    expect(postManagementPage).toContain('/system/posts/preview');
    expect(postManagementPage).toContain('metadata-only post catalog');
    expect(postManagementPage).toContain('noPersistence=true、noAssignment=true、noPermissionEffect=true');
    expect(postManagementPage).toContain('不代表组织权限组、岗位权限 runtime、用户岗位分配或 Workbench V3 全量完成');
    expect(postManagementPage).toContain('data-system-post-management="workbench-v3"');
    expect(postManagementPage).toContain('systemPostApi.list');
    expect(postManagementPage).toContain('systemPostApi.all');
    expect(postManagementPage).toContain('systemPostApi.getById');
    expect(postManagementPage).toContain('systemPostApi.meta');
    expect(postManagementPage).toContain('systemPostApi.preview');
    expect(postManagementPage).not.toMatch(/postApi|@\/api\/post|\.\.\/api\/post|assignUserPosts|getUserPostIds|routePermissions|workflowApi|@\/api\/workflow|auth\/login\/mobile|保存修改|删除|用户分配|权限授予/);
    expect(flowDefinitionPage).toContain('只读展示 /workflows 与 /workflows/{businessType}');
    expect(flowDefinitionPage).toContain('流程模板列表');
    expect(flowDefinitionPage).toContain('敏感细节已脱敏');
    expect(flowDefinitionPage).not.toMatch(/iframe|public\/mock/);
    expect(flowDesignerPage).toContain('真实调用 /workflows');
    expect(flowDesignerPage).toContain('/designer/draft');
    expect(flowDesignerPage).toContain('/designer/validate');
    expect(flowDesignerPage).toContain('/versions/');
    expect(flowDesignerPage).toContain('FlowCanvas');
    expect(flowDesignerPage).toContain('NodePanel');
    expect(flowDesignerPage).toContain('NodeConfigPanel');
    expect(flowDesignerPage).toContain('可视化流程画布');
    expect(flowDesignerPage).toContain('拖拽左侧节点到画布');
    expect(flowDesignerPage).toContain('保存草稿');
    expect(flowDesignerPage).toContain('图结构校验');
    expect(flowDesignerPage).toContain('发布流程');
    expect(flowDesignerPage).toContain('恢复最近版本');
    expect(flowDesignerPage).toContain('权限 fail-closed');
    expect(flowDesignerPage).not.toContain('节点/连线 DTO JSON');
    expect(flowDesignerPage).not.toMatch(/iframe|public\/mock/);
    expect(formConfigPage).toContain('真实调用 /form-definitions');
    expect(formConfigPage).toContain('/schema/validate');
    expect(formConfigPage).toContain('/publish');
    expect(formConfigPage).toContain('/disable');
    expect(formConfigPage).toContain('/versions/');
    expect(formConfigPage).toContain('/preview');
    expect(formConfigPage).toContain('/references');
    expect(formConfigPage).toContain('表单对象搜索');
    expect(formConfigPage).toContain('字段表');
    expect(formConfigPage).toContain('桌面预览');
    expect(formConfigPage).toContain('钉钉 H5 预览');
    expect(formConfigPage).toContain('字段属性');
    expect(formConfigPage).toContain('表单对象、字段列表、桌面预览、钉钉 H5 预览和字段属性同屏联动');
    expect(formConfigPage).toContain('保存草稿');
    expect(formConfigPage).toContain('schema 校验');
    expect(formConfigPage).toContain('发布表单');
    expect(formConfigPage).toContain('停用表单');
    expect(formConfigPage).toContain('恢复最近版本');
    expect(formConfigPage).toContain('权限 fail-closed');
    expect(formConfigPage).toContain('敏感字段默认值仅展示遮罩预览');
    expect(formConfigPage).not.toContain('表单 schema JSON');
    expect(formConfigPage).not.toMatch(/iframe|public\/mock/);
    expect(formStoragePage).toContain('真实调用 /form-storage');
    expect(formStoragePage).toContain('归档');
    expect(formStoragePage).toContain('删除留痕');
    expect(formStoragePage).toContain('附件引用');
    expect(formStoragePage).toContain('导出脱敏快照');
    expect(formStoragePage).toContain('服务层强制租户隔离');
    expect(formStoragePage).toContain('URL/storageKey 已脱敏');
    expect(formStoragePage).toContain('错误详情已脱敏');
    expect(formStoragePage).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=/);
    expect(approvalRulesPage).toContain('真实调用 /approval-rules');
    expect(approvalRulesPage).toContain('自有白名单 parser/evaluator');
    expect(approvalRulesPage).toContain('模拟命中');
    expect(approvalRulesPage).toContain('冲突检测');
    expect(approvalRulesPage).toContain('启用规则');
    expect(approvalRulesPage).toContain('停用规则');
    expect(approvalRulesPage).toContain('错误详情已脱敏');
    expect(approvalRulesPage).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=/);
    expect(todoFieldsPage).toContain('真实调用 /todo-fields');
    expect(todoFieldsPage).toContain('保存稳定排序');
    expect(todoFieldsPage).toContain('保存角色覆盖');
    expect(todoFieldsPage).toContain('恢复默认配置');
    expect(todoFieldsPage).toContain('敏感字段默认脱敏');
    expect(todoFieldsPage).toContain('错误详情已脱敏');
    expect(todoFieldsPage).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=/);
    expect(slaConfigPage).toContain('真实调用 /sla-config');
    expect(slaConfigPage).toContain('保存策略草稿');
    expect(slaConfigPage).toContain('启用策略');
    expect(slaConfigPage).toContain('停用策略');
    expect(slaConfigPage).toContain('运行模拟');
    expect(slaConfigPage).toContain('导出脱敏快照');
    expect(slaConfigPage).toContain('不发送真实通知');
    expect(slaConfigPage).toContain('错误详情已脱敏');
    expect(slaConfigPage).not.toMatch(/iframe|public\/mock|fixed-assets\/workbench\?menu=/);
    expect(runtimeMonitorPage).toContain('/sla-config/runtime-summary');
    expect(runtimeMonitorPage).toContain('审批实例列表');
    expect(runtimeMonitorPage).toContain('SLA 节点耗时');
    expect(runtimeMonitorPage).toContain('SLA 异常轨迹');
    expect(runtimeMonitorPage).toContain('敏感细节已脱敏');
    expect(runtimeMonitorPage).not.toMatch(/iframe|public\/mock/);
    expect(commandCenterPage).toContain('/sla-config/runtime-summary');
    expect(commandCenterPage).toContain('SLA 风险摘要与超时记录');
    expect(commandCenterPage).toContain('不支持发起/审批/重试/终止/发布/编辑，不代表流程控制闭环');
    expect(commandCenterPage).toContain('SLA 只读联动已纳入流程平台 9/9');
    expect(commandCenterPage).toContain('仍非 44 项全量覆盖，不代表 Workbench V3 全量完成');
    expect(commandCenterPage).not.toContain('PASS 后最多 9/9');
    expect(commandCenterPage).toContain('敏感细节已脱敏');
    expect(commandCenterPage).not.toMatch(/iframe|public\/mock/);
  });
});
